version: "3.9"

services:
  backend:
    container_name: backend
    build: ./backend
    environment:
      - PORT=8000
      - HOST=0.0.0.0
    ports:
      - "8000:8000"

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    environment:
      - VITE_SOCKET_SERVER_URL=backend:8000
    ports:
      - "3000:80"
